version: '3.9'

networks:
  SOFCopy:

services:
  web:
    depends_on:
      - db
      - redis
      - kc_db
      - keycloak
    build: .
    working_dir: /app
    command: uvicorn app.main:app --reload --host ${UVICORN_HOST} --port ${WEB_PORT_CONTAINER}
    volumes:
      - ".:/app/"
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_CONTAINER}
    container_name: web
    networks:
      - SOFCopy

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./databases3:/var/lib/postgresql/data/"
    container_name: db
    networks:
      - SOFCopy

  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - './redis_data3:/data/'
    container_name: redis
    networks:
      - SOFCopy

  kc_db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${KC_DB_PORT_HOST}:${KC_DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_DB=${KC_DB_NAME}
    volumes:
      - "./kc_databases3:/var/lib/postgresql/data/"
    container_name: kc_db
    networks:
      - SOFCopy

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - kc_db
    restart: always
    ports:
      - ${KEYCLOAK_PORT_HOST}:${KEYCLOAK_PORT_CONTAINER}
    environment:
      - KEYCLOAK_ADMIN=${SUPERUSER_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${SUPERUSER_PASSWORD}
      - KC_DB=postgres
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://kc_db/${KC_DB_NAME}
    command: start-dev
    volumes:
      - ./keycloak:/var/lib/keycloak/data/
    container_name: keycloak
    networks:
      - SOFCopy