version: '3.9'

networks:
  SOFCopy:

services:
  web:
    depends_on:
      - db
      - redis
      - kc_db
      - keycloak
    build: .
    working_dir: /app
    command: uvicorn app.main:app --reload --host ${UVICORN_HOST} --port ${WEB_PORT_CONTAINER}
    volumes:
      - ".:/app/"
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_CONTAINER}
    container_name: web
    networks:
      - SOFCopy

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./databases:/var/lib/postgresql/data/"
    container_name: db
    networks:
      - SOFCopy

  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - './redis_data:/data/'
    container_name: redis
    networks:
      - SOFCopy

  kc_db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${KC_DB_PORT_HOST}:${KC_DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_DB=${KC_DB_NAME}
    volumes:
      - "./kc_databases:/var/lib/postgresql/data/"
    container_name: kc_db
    networks:
      - SOFCopy

  keycloak:
    user: root
    build:
      context: .
      dockerfile: Dockerfile_keycloak
    depends_on:
      - kc_db
    restart: always
    ports:
      - ${KEYCLOAK_PORT_HOST}:${KEYCLOAK_PORT_CONTAINER}
    environment:
      - KEYCLOAK_ADMIN=${SUPERUSER_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${SUPERUSER_PASSWORD}
      - KC_DB=postgres
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_URL=jdbc:postgresql://kc_db/${KC_DB_NAME}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USERNAME=${EMAIL_SMTP_USERNAME}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
    container_name: keycloak
    networks:
      - SOFCopy