version: '3.9'

networks:
  SOFCopy:

services:
  web:
    depends_on:
      - db
      - redis
    build: .
    working_dir: /app
    command: uvicorn app.main:app --reload --host ${UVICORN_HOST} --port ${WEB_PORT_CONTAINER}
    volumes:
      - ".:/app/"
    ports:
      - ${WEB_PORT_HOST}:${WEB_PORT_CONTAINER}
    container_name: web
    networks:
      - SOFCopy

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./databases:/var/lib/postgresql/data/"
    container_name: db
    networks:
      - SOFCopy

  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - ${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - './redis_data:/data/'
    container_name: redis
    networks:
      - SOFCopy
