"""fixed unique constraint in vote model

Revision ID: 1d9d7a3e2132
Revises: d8356bfbed40
Create Date: 2024-08-05 13:17:17.490392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9d7a3e2132'
down_revision: Union[str, None] = 'd8356bfbed40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('votes_user_id_answer_id_key', 'votes', type_='unique')
    op.drop_constraint('votes_user_id_question_id_key', 'votes', type_='unique')
    op.create_unique_constraint('unique_user_vote', 'votes', ['user_id', 'question_id', 'answer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_vote', 'votes', type_='unique')
    op.create_unique_constraint('votes_user_id_question_id_key', 'votes', ['user_id', 'question_id'])
    op.create_unique_constraint('votes_user_id_answer_id_key', 'votes', ['user_id', 'answer_id'])
    # ### end Alembic commands ###
