"""added created_at column in question_tag table

Revision ID: 7b3f54075dc6
Revises: 47bcf4b67fac
Create Date: 2024-09-03 11:44:05.397001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3f54075dc6'
down_revision: Union[str, None] = '47bcf4b67fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_tag', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_tag', 'created_at')
    # ### end Alembic commands ###
