"""redesign storage tables

Revision ID: b262580b293b
Revises: e1f12164a399
Create Date: 2024-08-29 07:27:12.877711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b262580b293b'
down_revision: Union[str, None] = 'e1f12164a399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_file_name', sa.String(), nullable=False),
    sa.Column('stored_file_name', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_items_id'), 'storage_items', ['id'], unique=False)
    op.drop_index('ix_s3_files_id', table_name='s3_files')
    op.drop_table('s3_files')
    op.add_column('users', sa.Column('avatar_file_storage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'storage_items', ['avatar_file_storage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_file_storage_id')
    op.create_table('s3_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folder', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='s3_files_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='s3_files_pkey')
    )
    op.create_index('ix_s3_files_id', 's3_files', ['id'], unique=False)
    op.drop_index(op.f('ix_storage_items_id'), table_name='storage_items')
    op.drop_table('storage_items')
    # ### end Alembic commands ###
