"""added external_id column to users table

Revision ID: dff5705965f4
Revises: e34b6ab5c1cc
Create Date: 2024-09-05 11:52:21.315343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff5705965f4'
down_revision: Union[str, None] = 'e34b6ab5c1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE users SET external_id = id WHERE id = 1')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'external_id')
    # ### end Alembic commands ###
