"""implement s3 file model

Revision ID: e1f12164a399
Revises: 5ed2449e33c2
Create Date: 2024-08-23 07:17:51.773991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f12164a399'
down_revision: Union[str, None] = '5ed2449e33c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_files_id'), 's3_files', ['id'], unique=False)
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_s3_files_id'), table_name='s3_files')
    op.drop_table('s3_files')
    # ### end Alembic commands ###
