"""deleted password field in users table

Revision ID: e34b6ab5c1cc
Revises: f4fd27769b44
Create Date: 2024-08-27 09:46:11.372634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34b6ab5c1cc'
down_revision: Union[str, None] = 'f4fd27769b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("UPDATE users SET password = '' WHERE password IS NULL")
    # ### end Alembic commands ###
